name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, 386, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build binaries
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-X bruno-init-suite/internal/version.Version=${{ github.ref }}" -o build/bruno-init-suite-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Archive binaries
        run: |
          cd build
          for FILE in *; do
            if [[ $FILE == *.exe ]]; then
              zip "${FILE}.zip" "$FILE"
            else
              tar -czvf "${FILE}.tar.gz" "$FILE"
            fi
          done

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}
          release_id: ${{ github.event.release.id }}
          asset_path: build/*
          asset_name: ${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.sha }}
          asset_content_type: application/zip